# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ophir\PycharmProjects\facedetectionexample\pictures\ListUsers.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

#יוצר את הגרפיקה של הDialog של צפיה בכל המתשמשים ב DB
class Ui_DialogList(object):
    def setupUi(self, DialogList):
        DialogList.setObjectName("DialogList")
        DialogList.resize(465, 404)
        self.tableWidget = QtWidgets.QTableWidget(DialogList)
        self.tableWidget.setGeometry(QtCore.QRect(30, 30, 401, 351))
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")

        self.retranslateUi(DialogList)
        QtCore.QMetaObject.connectSlotsByName(DialogList)

    def retranslateUi(self, DialogList):
        _translate = QtCore.QCoreApplication.translate
        DialogList.setWindowTitle(_translate("DialogList", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogList = QtWidgets.QDialog()
    ui = Ui_DialogList()
    ui.setupUi(DialogList)
    DialogList.show()
    sys.exit(app.exec_())
